FROM python:2.7.13

MAINTAINER egg.tsai@tripleonetech.net

RUN ln -sf /usr/share/zoneinfo/Asia/Taipei  /etc/localtime

Run pip install MySQL-python && \
	pip install python-Levenshtein && \
	pip install futures && \
	pip install multiprocess
	
COPY ./userid_ip_matching.py ./userid_ip_matching.py
COPY ./MySQL_Operate.py ./MySQL_Operate.py

CMD ["python", "userid_ip_matching.py"]